"""add_phase_6_and_capture_plan_tables

Revision ID: 00dc3fd655db
Revises: c62fd797e0ff
Create Date: 2025-11-29 15:20:00.152870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dc3fd655db'
down_revision: Union[str, None] = 'c62fd797e0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('shipley_phase', sa.String(), nullable=True))
    op.add_column('proposals', sa.Column('capture_manager_id', sa.String(), nullable=True))
    op.add_column('proposals', sa.Column('pmp_data', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('proposals', sa.Column('bid_decision_score', sa.Float(), nullable=True))
    op.add_column('proposals', sa.Column('bid_decision_justification', sa.Text(), nullable=True))
    op.add_column('proposals', sa.Column('bid_decision_date', sa.DateTime(), nullable=True))
    op.add_column('proposals', sa.Column('bid_decision_by', sa.String(), nullable=True))
    
    op.create_index(op.f('ix_proposals_shipley_phase'), 'proposals', ['shipley_phase'], unique=False)
    op.add_column('stored_files', sa.Column('version_number', sa.String(), server_default='1', nullable=True))
    op.create_index(op.f('ix_stored_files_version_number'), 'stored_files', ['version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_files_version_number'), table_name='stored_files')
    op.alter_column('stored_files', 'version_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_proposals_shipley_phase'), table_name='proposals')
    # ### end Alembic commands ###
