"""add_phase_6_and_capture_plan_tables

Revision ID: 00dc3fd655db
Revises: c62fd797e0ff
Create Date: 2025-11-29 15:20:00.152870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dc3fd655db'
down_revision: Union[str, None] = 'c62fd797e0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_proposals_shipley_phase'), 'proposals', ['shipley_phase'], unique=False)
    op.alter_column('stored_files', 'version_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_stored_files_version_number'), 'stored_files', ['version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_files_version_number'), table_name='stored_files')
    op.alter_column('stored_files', 'version_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_proposals_shipley_phase'), table_name='proposals')
    # ### end Alembic commands ###
