"""add_opportunity_pipeline_model

Revision ID: 1bac2dc93831
Revises: edd905c54e16
Create Date: 2025-11-26 22:30:01.663670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1bac2dc93831'
down_revision: Union[str, None] = 'edd905c54e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('questions_due_date', sa.DateTime(), nullable=True),
    sa.Column('proposal_due_date', sa.DateTime(), nullable=True),
    sa.Column('submission_instructions', sa.Text(), nullable=True),
    sa.Column('required_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_pipelines_id'), 'opportunity_pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_pipelines_opportunity_id'), 'opportunity_pipelines', ['opportunity_id'], unique=True)
    op.create_table('company_profile_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_uei', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_uei'], ['company_profiles.uei'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profile_documents_company_uei'), 'company_profile_documents', ['company_uei'], unique=False)
    op.create_index(op.f('ix_company_profile_documents_document_type'), 'company_profile_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_company_profile_documents_id'), 'company_profile_documents', ['id'], unique=False)
    op.create_table('company_profile_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_uei', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_uei'], ['company_profiles.uei'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profile_links_company_uei'), 'company_profile_links', ['company_uei'], unique=False)
    op.create_index(op.f('ix_company_profile_links_id'), 'company_profile_links', ['id'], unique=False)
    op.create_index(op.f('ix_company_profile_links_link_type'), 'company_profile_links', ['link_type'], unique=False)
    op.add_column('company_profiles', sa.Column('entity_uei', sa.String(), nullable=True))
    op.create_index(op.f('ix_company_profiles_entity_uei'), 'company_profiles', ['entity_uei'], unique=False)
    op.create_foreign_key(None, 'company_profiles', 'entities', ['entity_uei'], ['uei'])
    op.add_column('entity_awards', sa.Column('award_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_awards', 'award_type')
    op.drop_constraint(None, 'company_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_company_profiles_entity_uei'), table_name='company_profiles')
    op.drop_column('company_profiles', 'entity_uei')
    op.drop_index(op.f('ix_company_profile_links_link_type'), table_name='company_profile_links')
    op.drop_index(op.f('ix_company_profile_links_id'), table_name='company_profile_links')
    op.drop_index(op.f('ix_company_profile_links_company_uei'), table_name='company_profile_links')
    op.drop_table('company_profile_links')
    op.drop_index(op.f('ix_company_profile_documents_id'), table_name='company_profile_documents')
    op.drop_index(op.f('ix_company_profile_documents_document_type'), table_name='company_profile_documents')
    op.drop_index(op.f('ix_company_profile_documents_company_uei'), table_name='company_profile_documents')
    op.drop_table('company_profile_documents')
    op.drop_index(op.f('ix_opportunity_pipelines_opportunity_id'), table_name='opportunity_pipelines')
    op.drop_index(op.f('ix_opportunity_pipelines_id'), table_name='opportunity_pipelines')
    op.drop_table('opportunity_pipelines')
    # ### end Alembic commands ###
