"""add_agent_and_proposal_tables

Revision ID: 1c9dd934677d
Revises: 2a9c09c3fec6
Create Date: 2025-11-23 16:41:24.423534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9dd934677d'
down_revision: Union[str, None] = '2a9c09c3fec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
