"""add naics_code to entity_award

Revision ID: 200e40831c66
Revises: ffd70edccbcd
Create Date: 2025-11-21 22:45:03.490165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200e40831c66'
down_revision: Union[str, None] = 'ffd70edccbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_awards', sa.Column('naics_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_entity_awards_naics_code'), 'entity_awards', ['naics_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_awards_naics_code'), table_name='entity_awards')
    op.drop_column('entity_awards', 'naics_code')
    # ### end Alembic commands ###
