"""Add compliance_status and risk_score columns

Revision ID: 2a9c09c3fec6
Revises: 392863bada93
Create Date: 2025-11-23 15:58:37.412259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9c09c3fec6'
down_revision: Union[str, None] = '392863bada93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('compliance_status', sa.String(), server_default='PENDING', nullable=True))
    op.add_column('opportunities', sa.Column('risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'risk_score')
    op.drop_column('opportunities', 'compliance_status')
    # ### end Alembic commands ###
