"""add_analysis_json_to_stored_file

Revision ID: 42966457dabe
Revises: caa6938e25f5
Create Date: 2025-11-21 15:09:40.466885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '42966457dabe'
down_revision: Union[str, None] = 'caa6938e25f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_files', sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stored_files', 'analysis_json')
    # ### end Alembic commands ###
