"""add award_type to entity_awards

Revision ID: 51c483864494
Revises: d9ff2b142576
Create Date: 2025-11-26 15:53:51.388209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c483864494'
down_revision: Union[str, None] = 'd9ff2b142576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_awards', sa.Column('award_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_entity_awards_naics_code'), 'entity_awards', ['naics_code'], unique=False)
    op.create_index(op.f('ix_entity_awards_solicitation_id'), 'entity_awards', ['solicitation_id'], unique=False)
    op.alter_column('opportunities', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunities', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_entity_awards_solicitation_id'), table_name='entity_awards')
    op.drop_index(op.f('ix_entity_awards_naics_code'), table_name='entity_awards')
    op.drop_column('entity_awards', 'award_type')
    # ### end Alembic commands ###
