"""add contracting_officers table

Revision ID: 60666958a0ec
Revises: a4ca44385ced
Create Date: 2025-12-11 04:12:32.065867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60666958a0ec'
down_revision: Union[str, None] = 'a4ca44385ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_artifacts_type'), table_name='document_artifacts')
    op.create_index(op.f('ix_document_artifacts_id'), 'document_artifacts', ['id'], unique=False)
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('section', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'section')
    op.drop_column('document_chunks', 'page_number')
    op.drop_index(op.f('ix_document_artifacts_id'), table_name='document_artifacts')
    op.create_index(op.f('ix_document_artifacts_type'), 'document_artifacts', ['artifact_type'], unique=False)
    # ### end Alembic commands ###
