"""add_partner_search_fields_and_team_models

Revision ID: 93062ca5af9c
Revises: d2bd61f6c9bf
Create Date: 2025-12-01 15:39:08.957907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '93062ca5af9c'
down_revision: Union[str, None] = 'd2bd61f6c9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_teams_id'), 'opportunity_teams', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_teams_opportunity_id'), 'opportunity_teams', ['opportunity_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('entity_uei', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('capabilities_contribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_uei'], ['entities.uei'], ),
    sa.ForeignKeyConstraint(['team_id'], ['opportunity_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_entity_uei'), 'team_members', ['entity_uei'], unique=False)
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.add_column('entities', sa.Column('revenue', sa.Float(), nullable=True))
    op.add_column('entities', sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entities', sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entities', sa.Column('web_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entities', sa.Column('personnel_count', sa.Integer(), nullable=True))
    op.add_column('entities', sa.Column('business_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'business_types')
    op.drop_column('entities', 'personnel_count')
    op.drop_column('entities', 'web_addresses')
    op.drop_column('entities', 'locations')
    op.drop_column('entities', 'capabilities')
    op.drop_column('entities', 'revenue')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_entity_uei'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_opportunity_teams_opportunity_id'), table_name='opportunity_teams')
    op.drop_index(op.f('ix_opportunity_teams_id'), table_name='opportunity_teams')
    op.drop_table('opportunity_teams')
    # ### end Alembic commands ###
