"""add_solicitation_id_to_entity_award

Revision ID: 95811563a58e
Revises: 1c9dd934677d
Create Date: 2025-11-23 22:34:25.155275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95811563a58e'
down_revision: Union[str, None] = '1c9dd934677d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_awards', sa.Column('solicitation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_entity_awards_solicitation_id'), 'entity_awards', ['solicitation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_awards_solicitation_id'), table_name='entity_awards')
    op.drop_column('entity_awards', 'solicitation_id')
    # ### end Alembic commands ###
