"""add_perplexity_competitor_analysis_table

Revision ID: a4ca44385ced
Revises: 93062ca5af9c
Create Date: 2025-12-08 16:36:30.800305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a4ca44385ced'
down_revision: Union[str, None] = '93062ca5af9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perplexity_competitor_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_uei', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('market_position', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_differentiators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategies_to_beat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_uei'], ['entities.uei'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perplexity_competitor_analyses_entity_name'), 'perplexity_competitor_analyses', ['entity_name'], unique=False)
    op.create_index(op.f('ix_perplexity_competitor_analyses_entity_uei'), 'perplexity_competitor_analyses', ['entity_uei'], unique=False)
    op.create_index(op.f('ix_perplexity_competitor_analyses_id'), 'perplexity_competitor_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_perplexity_competitor_analyses_opportunity_id'), 'perplexity_competitor_analyses', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perplexity_competitor_analyses_opportunity_id'), table_name='perplexity_competitor_analyses')
    op.drop_index(op.f('ix_perplexity_competitor_analyses_id'), table_name='perplexity_competitor_analyses')
    op.drop_index(op.f('ix_perplexity_competitor_analyses_entity_uei'), table_name='perplexity_competitor_analyses')
    op.drop_index(op.f('ix_perplexity_competitor_analyses_entity_name'), table_name='perplexity_competitor_analyses')
    op.drop_table('perplexity_competitor_analyses')
    # ### end Alembic commands ###
