"""add_archive_fields_to_pipeline

Revision ID: a85a74a22990
Revises: f6a74aaee1ef
Create Date: 2025-11-30 09:41:13.665399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a85a74a22990'
down_revision: Union[str, None] = 'f6a74aaee1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_document_artifacts_type'), table_name='document_artifacts')
    op.create_index(op.f('ix_document_artifacts_id'), 'document_artifacts', ['id'], unique=False)
    op.drop_constraint(op.f('document_artifacts_proposal_id_fkey'), 'document_artifacts', type_='foreignkey')
    op.drop_constraint(op.f('document_artifacts_file_id_fkey'), 'document_artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'document_artifacts', 'stored_files', ['file_id'], ['id'])
    op.create_foreign_key(None, 'document_artifacts', 'proposals', ['proposal_id'], ['id'])
    op.add_column('opportunity_pipelines', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('opportunity_pipelines', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('opportunity_pipelines', sa.Column('archived_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_opportunity_pipelines_archived'), 'opportunity_pipelines', ['archived'], unique=False)
    op.alter_column('proposal_requirements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('proposal_requirements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_proposal_requirements_status'), table_name='proposal_requirements')
    op.drop_index(op.f('ix_proposal_requirements_type'), table_name='proposal_requirements')
    op.create_index(op.f('ix_proposal_requirements_id'), 'proposal_requirements', ['id'], unique=False)
    op.drop_constraint(op.f('proposal_requirements_source_document_id_fkey'), 'proposal_requirements', type_='foreignkey')
    op.drop_constraint(op.f('proposal_requirements_proposal_id_fkey'), 'proposal_requirements', type_='foreignkey')
    op.create_foreign_key(None, 'proposal_requirements', 'proposals', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'proposal_requirements', 'stored_files', ['source_document_id'], ['id'])
    op.alter_column('requirement_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('requirement_responses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_requirement_responses_id'), 'requirement_responses', ['id'], unique=False)
    op.drop_constraint(op.f('requirement_responses_requirement_id_fkey'), 'requirement_responses', type_='foreignkey')
    op.create_foreign_key(None, 'requirement_responses', 'proposal_requirements', ['requirement_id'], ['id'])
    op.add_column('stored_files', sa.Column('status', sa.String(), nullable=True))
    op.add_column('stored_files', sa.Column('checked_out_by', sa.String(), nullable=True))
    op.add_column('stored_files', sa.Column('checked_out_at', sa.DateTime(), nullable=True))
    op.add_column('stored_files', sa.Column('s3_uri', sa.String(), nullable=True))
    op.add_column('stored_files', sa.Column('parent_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stored_files', 'stored_files', ['parent_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stored_files', type_='foreignkey')
    op.drop_column('stored_files', 'parent_file_id')
    op.drop_column('stored_files', 's3_uri')
    op.drop_column('stored_files', 'checked_out_at')
    op.drop_column('stored_files', 'checked_out_by')
    op.drop_column('stored_files', 'status')
    op.drop_constraint(None, 'requirement_responses', type_='foreignkey')
    op.create_foreign_key(op.f('requirement_responses_requirement_id_fkey'), 'requirement_responses', 'proposal_requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_requirement_responses_id'), table_name='requirement_responses')
    op.alter_column('requirement_responses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('requirement_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'proposal_requirements', type_='foreignkey')
    op.drop_constraint(None, 'proposal_requirements', type_='foreignkey')
    op.create_foreign_key(op.f('proposal_requirements_proposal_id_fkey'), 'proposal_requirements', 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('proposal_requirements_source_document_id_fkey'), 'proposal_requirements', 'stored_files', ['source_document_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_proposal_requirements_id'), table_name='proposal_requirements')
    op.create_index(op.f('ix_proposal_requirements_type'), 'proposal_requirements', ['requirement_type'], unique=False)
    op.create_index(op.f('ix_proposal_requirements_status'), 'proposal_requirements', ['compliance_status'], unique=False)
    op.alter_column('proposal_requirements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('proposal_requirements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_opportunity_pipelines_archived'), table_name='opportunity_pipelines')
    op.drop_column('opportunity_pipelines', 'archived_by')
    op.drop_column('opportunity_pipelines', 'archived_at')
    op.drop_column('opportunity_pipelines', 'archived')
    op.drop_constraint(None, 'document_artifacts', type_='foreignkey')
    op.drop_constraint(None, 'document_artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('document_artifacts_file_id_fkey'), 'document_artifacts', 'stored_files', ['file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('document_artifacts_proposal_id_fkey'), 'document_artifacts', 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_artifacts_id'), table_name='document_artifacts')
    op.create_index(op.f('ix_document_artifacts_type'), 'document_artifacts', ['artifact_type'], unique=False)
    op.alter_column('document_artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
