"""add_shipley_workflow_tables

Revision ID: c62fd797e0ff
Revises: 664fba81bb6f
Create Date: 2025-11-28 14:43:10.740025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c62fd797e0ff'
down_revision: Union[str, None] = '664fba81bb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_no_bid_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('win_probability_score', sa.Float(), nullable=True),
    sa.Column('competitive_landscape_score', sa.Float(), nullable=True),
    sa.Column('incumbent_advantage_score', sa.Float(), nullable=True),
    sa.Column('technical_capability_score', sa.Float(), nullable=True),
    sa.Column('past_performance_relevance_score', sa.Float(), nullable=True),
    sa.Column('resource_availability_score', sa.Float(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('contract_value_score', sa.Float(), nullable=True),
    sa.Column('strategic_alignment_score', sa.Float(), nullable=True),
    sa.Column('agency_relationship_score', sa.Float(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('position_weight', sa.Float(), nullable=True),
    sa.Column('capability_weight', sa.Float(), nullable=True),
    sa.Column('attractiveness_weight', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_index(op.f('ix_bid_no_bid_criteria_id'), 'bid_no_bid_criteria', ['id'], unique=False)
    op.create_table('competitive_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('competitor_uei', sa.String(), nullable=True),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('historical_wins', sa.Integer(), nullable=True),
    sa.Column('total_obligation', sa.Float(), nullable=True),
    sa.Column('win_probability_impact', sa.Float(), nullable=True),
    sa.Column('is_incumbent', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('naics_match', sa.String(), nullable=True),
    sa.Column('agency_match', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_uei'], ['entities.uei'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitive_intelligence_id'), 'competitive_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_competitive_intelligence_opportunity_id'), 'competitive_intelligence', ['opportunity_id'], unique=False)
    op.create_table('review_gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('gate_type', sa.String(), nullable=False),
    sa.Column('review_type', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('artifact_version_reviewed', sa.String(), nullable=True),
    sa.Column('decision_by', sa.String(), nullable=False),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_gates_id'), 'review_gates', ['id'], unique=False)
    op.create_index(op.f('ix_review_gates_proposal_id'), 'review_gates', ['proposal_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_gate_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('section_reference', sa.String(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['stored_files.id'], ),
    sa.ForeignKeyConstraint(['review_gate_id'], ['review_gates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_id'), 'review_comments', ['id'], unique=False)
    op.create_index(op.f('ix_review_comments_review_gate_id'), 'review_comments', ['review_gate_id'], unique=False)
    op.alter_column('document_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_document_artifacts_type'), table_name='document_artifacts')
    op.create_index(op.f('ix_document_artifacts_id'), 'document_artifacts', ['id'], unique=False)
    op.drop_constraint(op.f('document_artifacts_proposal_id_fkey'), 'document_artifacts', type_='foreignkey')
    op.drop_constraint(op.f('document_artifacts_file_id_fkey'), 'document_artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'document_artifacts', 'proposals', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'document_artifacts', 'stored_files', ['file_id'], ['id'])
    op.alter_column('proposal_requirements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('proposal_requirements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_proposal_requirements_status'), table_name='proposal_requirements')
    op.drop_index(op.f('ix_proposal_requirements_type'), table_name='proposal_requirements')
    op.create_index(op.f('ix_proposal_requirements_id'), 'proposal_requirements', ['id'], unique=False)
    op.drop_constraint(op.f('proposal_requirements_proposal_id_fkey'), 'proposal_requirements', type_='foreignkey')
    op.drop_constraint(op.f('proposal_requirements_source_document_id_fkey'), 'proposal_requirements', type_='foreignkey')
    op.create_foreign_key(None, 'proposal_requirements', 'proposals', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'proposal_requirements', 'stored_files', ['source_document_id'], ['id'])
    op.add_column('proposals', sa.Column('shipley_phase', sa.String(), nullable=True))
    op.add_column('proposals', sa.Column('capture_manager_id', sa.String(), nullable=True))
    op.add_column('proposals', sa.Column('pmp_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('proposals', sa.Column('bid_decision_score', sa.Float(), nullable=True))
    op.add_column('proposals', sa.Column('bid_decision_justification', sa.Text(), nullable=True))
    op.add_column('proposals', sa.Column('bid_decision_date', sa.DateTime(), nullable=True))
    op.add_column('proposals', sa.Column('bid_decision_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_proposals_shipley_phase'), 'proposals', ['shipley_phase'], unique=False)
    op.alter_column('requirement_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('requirement_responses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_requirement_responses_id'), 'requirement_responses', ['id'], unique=False)
    op.drop_constraint(op.f('requirement_responses_requirement_id_fkey'), 'requirement_responses', type_='foreignkey')
    op.create_foreign_key(None, 'requirement_responses', 'proposal_requirements', ['requirement_id'], ['id'])
    op.add_column('stored_files', sa.Column('version_number', sa.String(), nullable=True))
    op.add_column('stored_files', sa.Column('status', sa.String(), nullable=True))
    op.add_column('stored_files', sa.Column('checked_out_by', sa.String(), nullable=True))
    op.add_column('stored_files', sa.Column('checked_out_at', sa.DateTime(), nullable=True))
    op.add_column('stored_files', sa.Column('s3_uri', sa.String(), nullable=True))
    op.add_column('stored_files', sa.Column('parent_file_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stored_files_version_number'), 'stored_files', ['version_number'], unique=False)
    op.create_foreign_key(None, 'stored_files', 'stored_files', ['parent_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stored_files', type_='foreignkey')
    op.drop_index(op.f('ix_stored_files_version_number'), table_name='stored_files')
    op.drop_column('stored_files', 'parent_file_id')
    op.drop_column('stored_files', 's3_uri')
    op.drop_column('stored_files', 'checked_out_at')
    op.drop_column('stored_files', 'checked_out_by')
    op.drop_column('stored_files', 'status')
    op.drop_column('stored_files', 'version_number')
    op.drop_constraint(None, 'requirement_responses', type_='foreignkey')
    op.create_foreign_key(op.f('requirement_responses_requirement_id_fkey'), 'requirement_responses', 'proposal_requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_requirement_responses_id'), table_name='requirement_responses')
    op.alter_column('requirement_responses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('requirement_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_proposals_shipley_phase'), table_name='proposals')
    op.drop_column('proposals', 'bid_decision_by')
    op.drop_column('proposals', 'bid_decision_date')
    op.drop_column('proposals', 'bid_decision_justification')
    op.drop_column('proposals', 'bid_decision_score')
    op.drop_column('proposals', 'pmp_data')
    op.drop_column('proposals', 'capture_manager_id')
    op.drop_column('proposals', 'shipley_phase')
    op.drop_constraint(None, 'proposal_requirements', type_='foreignkey')
    op.drop_constraint(None, 'proposal_requirements', type_='foreignkey')
    op.create_foreign_key(op.f('proposal_requirements_source_document_id_fkey'), 'proposal_requirements', 'stored_files', ['source_document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('proposal_requirements_proposal_id_fkey'), 'proposal_requirements', 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_proposal_requirements_id'), table_name='proposal_requirements')
    op.create_index(op.f('ix_proposal_requirements_type'), 'proposal_requirements', ['requirement_type'], unique=False)
    op.create_index(op.f('ix_proposal_requirements_status'), 'proposal_requirements', ['compliance_status'], unique=False)
    op.alter_column('proposal_requirements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('proposal_requirements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'document_artifacts', type_='foreignkey')
    op.drop_constraint(None, 'document_artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('document_artifacts_file_id_fkey'), 'document_artifacts', 'stored_files', ['file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('document_artifacts_proposal_id_fkey'), 'document_artifacts', 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_artifacts_id'), table_name='document_artifacts')
    op.create_index(op.f('ix_document_artifacts_type'), 'document_artifacts', ['artifact_type'], unique=False)
    op.alter_column('document_artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_review_comments_review_gate_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_review_gates_proposal_id'), table_name='review_gates')
    op.drop_index(op.f('ix_review_gates_id'), table_name='review_gates')
    op.drop_table('review_gates')
    op.drop_index(op.f('ix_competitive_intelligence_opportunity_id'), table_name='competitive_intelligence')
    op.drop_index(op.f('ix_competitive_intelligence_id'), table_name='competitive_intelligence')
    op.drop_table('competitive_intelligence')
    op.drop_index(op.f('ix_bid_no_bid_criteria_id'), table_name='bid_no_bid_criteria')
    op.drop_table('bid_no_bid_criteria')
    # ### end Alembic commands ###
