"""add opportunity_id to stored_files

Revision ID: caa6938e25f5
Revises: b21bab4bf745
Create Date: 2025-11-20 23:08:36.179119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa6938e25f5'
down_revision: Union[str, None] = 'b21bab4bf745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_files', sa.Column('opportunity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stored_files', 'opportunities', ['opportunity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stored_files', type_='foreignkey')
    op.drop_column('stored_files', 'opportunity_id')
    # ### end Alembic commands ###
