"""initial_schema_clean

Revision ID: d3260b57eb40
Revises: 
Create Date: 2025-11-18 22:52:20.395536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd3260b57eb40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.String(), nullable=True),
    sa.Column('solicitation_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('sub_tier', sa.String(), nullable=True),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('base_type', sa.String(), nullable=True),
    sa.Column('archive_type', sa.String(), nullable=True),
    sa.Column('archive_date', sa.DateTime(), nullable=True),
    sa.Column('type_of_set_aside_description', sa.String(), nullable=True),
    sa.Column('type_of_set_aside', sa.String(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(), nullable=True),
    sa.Column('naics_code', sa.String(), nullable=True),
    sa.Column('classification_code', sa.String(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('award', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('point_of_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization_type', sa.String(), nullable=True),
    sa.Column('office_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('place_of_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_info_link', sa.String(), nullable=True),
    sa.Column('ui_link', sa.String(), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_links', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('full_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_department'), 'opportunities', ['department'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_naics_code'), 'opportunities', ['naics_code'], unique=False)
    op.create_index(op.f('ix_opportunities_notice_id'), 'opportunities', ['notice_id'], unique=True)
    op.create_index(op.f('ix_opportunities_posted_date'), 'opportunities', ['posted_date'], unique=False)
    op.create_index(op.f('ix_opportunities_solicitation_number'), 'opportunities', ['solicitation_number'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_solicitation_number'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_posted_date'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_notice_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_naics_code'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_department'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
