"""Add CompanyProfile, Entity, EntityAward models

Revision ID: dad611f451e6
Revises: d3260b57eb40
Create Date: 2025-11-19 10:23:51.126367

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import orm
from sqlalchemy import Column, Integer, String, DateTime, Boolean, ARRAY, Text, ForeignKey, Float, Date
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad611f451e6'
down_revision: Union[str, None] = 'd3260b57eb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uei', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('target_naics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_set_asides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_id'), 'company_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_company_profiles_uei'), 'company_profiles', ['uei'], unique=True)
    op.create_table('entities',
    sa.Column('uei', sa.String(), nullable=False),
    sa.Column('legal_business_name', sa.String(), nullable=False),
    sa.Column('cage_code', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uei')
    )
    op.create_index(op.f('ix_entities_uei'), 'entities', ['uei'], unique=False)
    op.create_table('entity_awards',
    sa.Column('award_id', sa.String(), nullable=False),
    sa.Column('recipient_uei', sa.String(), nullable=True),
    sa.Column('total_obligation', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('awarding_agency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_uei'], ['entities.uei'], ),
    sa.PrimaryKeyConstraint('award_id')
    )
    op.create_index(op.f('ix_entity_awards_award_id'), 'entity_awards', ['award_id'], unique=False)
    op.create_index(op.f('ix_entity_awards_recipient_uei'), 'entity_awards', ['recipient_uei'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_awards_recipient_uei'), table_name='entity_awards')
    op.drop_index(op.f('ix_entity_awards_award_id'), table_name='entity_awards')
    op.drop_table('entity_awards')
    op.drop_index(op.f('ix_entities_uei'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_company_profiles_uei'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
