"""Add resource_files to Opportunity

Revision ID: dffe91f73935
Revises: 33161ae4caa2
Create Date: 2025-11-20 22:13:58.874029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffe91f73935'
down_revision: Union[str, None] = '33161ae4caa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('resource_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'resource_files')
    # ### end Alembic commands ###
