"""Add ProposalStage and Workflow fields

Revision ID: eb45098e4e3c
Revises: a1b2c3d4e5f6
Create Date: 2025-12-15 14:44:27.630860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'eb45098e4e3c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enum type manually
    proposal_stage_enum = postgresql.ENUM('DISCOVERY', 'ANALYSIS', 'DECOMPOSITION', 'STRATEGY', 'DRAFTING', 'REVIEW', 'APPROVAL', 'SUBMISSION', name='proposal_stage_enum')
    proposal_stage_enum.create(op.get_bind())
    
    op.add_column('past_performances', sa.Column('citations_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('past_performances', sa.Column('solicitation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_past_performances_source_document_id'), 'past_performances', ['source_document_id'], unique=False)
    op.add_column('proposals', sa.Column('current_stage', sa.Enum('DISCOVERY', 'ANALYSIS', 'DECOMPOSITION', 'STRATEGY', 'DRAFTING', 'REVIEW', 'APPROVAL', 'SUBMISSION', name='proposal_stage_enum'), nullable=True))
    op.add_column('proposals', sa.Column('stage_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_proposals_current_stage'), 'proposals', ['current_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_current_stage'), table_name='proposals')
    op.drop_column('proposals', 'stage_status')
    op.drop_column('proposals', 'current_stage')
    
    # Drop Enum type
    proposal_stage_enum = postgresql.ENUM('DISCOVERY', 'ANALYSIS', 'DECOMPOSITION', 'STRATEGY', 'DRAFTING', 'REVIEW', 'APPROVAL', 'SUBMISSION', name='proposal_stage_enum')
    proposal_stage_enum.drop(op.get_bind())
    
    op.drop_index(op.f('ix_past_performances_source_document_id'), table_name='past_performances')
    op.drop_column('past_performances', 'solicitation_context')
    op.drop_column('past_performances', 'citations_data')
    # ### end Alembic commands ###
