"""Add Proposal and ProposalVolume models

Revision ID: eb63222ac3ad
Revises: 200e40831c66
Create Date: 2025-11-23 15:38:25.326373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'eb63222ac3ad'
down_revision: Union[str, None] = '200e40831c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_activity_logs_id'), 'agent_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_activity_logs_opportunity_id'), 'agent_activity_logs', ['opportunity_id'], unique=False)
    op.create_table('opportunity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('strategic_alignment_score', sa.Float(), nullable=True),
    sa.Column('financial_viability_score', sa.Float(), nullable=True),
    sa.Column('contract_risk_score', sa.Float(), nullable=True),
    sa.Column('internal_capacity_score', sa.Float(), nullable=True),
    sa.Column('data_integrity_score', sa.Float(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('go_no_go_decision', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_index(op.f('ix_opportunity_scores_id'), 'opportunity_scores', ['id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_opportunity_id'), 'proposals', ['opportunity_id'], unique=False)
    op.create_table('proposal_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_volumes_id'), 'proposal_volumes', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_volumes_proposal_id'), 'proposal_volumes', ['proposal_id'], unique=False)
    op.add_column('opportunities', sa.Column('compliance_status', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'risk_score')
    op.drop_column('opportunities', 'compliance_status')
    op.drop_index(op.f('ix_proposal_volumes_proposal_id'), table_name='proposal_volumes')
    op.drop_index(op.f('ix_proposal_volumes_id'), table_name='proposal_volumes')
    op.drop_table('proposal_volumes')
    op.drop_index(op.f('ix_proposals_opportunity_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_opportunity_scores_id'), table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index(op.f('ix_agent_activity_logs_opportunity_id'), table_name='agent_activity_logs')
    op.drop_index(op.f('ix_agent_activity_logs_id'), table_name='agent_activity_logs')
    op.drop_table('agent_activity_logs')
    # ### end Alembic commands ###
