"""add_manual_ingest_fields

Revision ID: f38e8e5cf21c
Revises: a85a74a22990
Create Date: 2025-12-01 09:09:15.865792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38e8e5cf21c'
down_revision: Union[str, None] = 'a85a74a22990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('source', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('incumbent_vendor', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('incumbent_contract_number', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('incumbent_value', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('incumbent_expiration_date', sa.DateTime(), nullable=True))
    op.add_column('opportunities', sa.Column('previous_sow_document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opportunities', 'stored_files', ['previous_sow_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'previous_sow_document_id')
    op.drop_column('opportunities', 'incumbent_expiration_date')
    op.drop_column('opportunities', 'incumbent_value')
    op.drop_column('opportunities', 'incumbent_contract_number')
    op.drop_column('opportunities', 'incumbent_vendor')
    op.drop_column('opportunities', 'source')
    # ### end Alembic commands ###
