"""add is_primary to entity

Revision ID: ffd70edccbcd
Revises: 264d5a4ff3c9
Create Date: 2025-11-21 22:42:26.849772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd70edccbcd'
down_revision: Union[str, None] = '264d5a4ff3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('is_primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'is_primary')
    # ### end Alembic commands ###
