import { Slideout } from '@/components/ui/slideout';
import { Button } from '@/components/ui/button';
import { FileText, Download } from 'lucide-react';

interface QuickScanSlideoutProps {
    isOpen: boolean;
    onClose: () => void;
    htmlContent: string;
}

export default function QuickScanSlideout({ isOpen, onClose, htmlContent }: QuickScanSlideoutProps) {

    const handleDownload = () => {
        const blob = new Blob([htmlContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'quick_scan_summary.html';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <Slideout
            isOpen={isOpen}
            onClose={onClose}
            title="Quick Scan Summary"
            width="max-w-3xl"
        >
            <div className="space-y-6">
                <div className="flex items-center justify-between border-b pb-4">
                    <div className="flex items-center gap-2 text-primary">
                        <FileText className="h-5 w-5" />
                        <span className="font-semibold">generated by Government ContractingGPT</span>
                    </div>
                    <Button variant="outline" size="sm" onClick={handleDownload} className="gap-2">
                        <Download className="h-4 w-4" />
                        Download HTML
                    </Button>
                </div>

                {/* Theme-adaptive container for AI-generated HTML content */}
                <div
                    className="bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700"
                >
                    <style>{`
                        .quick-scan-content h1, .quick-scan-content h2, .quick-scan-content h3 {
                            color: inherit;
                        }
                        .quick-scan-content p, .quick-scan-content li, .quick-scan-content td {
                            color: inherit;
                        }
                        .quick-scan-content table {
                            border-color: currentColor;
                        }
                        .quick-scan-content td, .quick-scan-content tr {
                            border-color: rgba(128, 128, 128, 0.3);
                        }
                        .dark .quick-scan-content [style*="background: #f8fafc"],
                        .dark .quick-scan-content [style*="background:#f8fafc"] {
                            background: #1f2937 !important;
                        }
                        .dark .quick-scan-content [style*="background: linear-gradient"] {
                            background: linear-gradient(135deg, #1e3a5f, #1d4ed8) !important;
                        }
                        .dark .quick-scan-content [style*="color: #333"],
                        .dark .quick-scan-content [style*="color:#333"] {
                            color: #e5e7eb !important;
                        }
                        .dark .quick-scan-content [style*="color: #64748b"] {
                            color: #9ca3af !important;
                        }
                        .dark .quick-scan-content [style*="color: #1e3a5f"] {
                            color: #93c5fd !important;
                        }
                        .dark .quick-scan-content [style*="border: 1px solid #e2e8f0"] {
                            border-color: #374151 !important;
                        }
                        .dark .quick-scan-content [style*="background: #fef3c7"] {
                            background: #422006 !important;
                        }
                        .dark .quick-scan-content [style*="color: #92400e"],
                        .dark .quick-scan-content [style*="color: #78350f"] {
                            color: #fbbf24 !important;
                        }
                    `}</style>
                    <div className="quick-scan-content" dangerouslySetInnerHTML={{ __html: htmlContent }} />
                </div>

                <div className="pt-8 border-t">
                    <Button onClick={onClose} className="w-full">Close Summary</Button>
                </div>
            </div>
        </Slideout>
    );
}
